app_home:
  path: /
  controller: App\Controller\PinsController::index
  methods: GET
app_pins_create:
  path: /pins/create
  controller: App\Controller\PinsController::create
  methods: GET|POST

app_pins_show:
  path: /pins/{id<[0-9]+>}
  controller: App\Controller\PinsController::show
  methods: GET
  
  


#index:
#    path: /
#    controller: App\Controller\DefaultController::index
