app_home:
  path: /
  controller: App\Controller\PinsController::index
  methods: GET
  

app_pins_create:
  path: /pins/create
  controller: App\Controller\PinsController::create
  methods: GET|POST
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
